# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b1bc5efd5eb56485d6f22efec72b12e580cca309bb83e576fe89d4d28f97b8bc07756a3e7ba3c8451e3520c542a0e6bee43d12fd28cca80e18ca3355ec50bd

test:
  secret_key_base: 5d98075a3dadec52240b6e782c9fa25e9b9c19240f1705edaa706d5605921c4b1bfcbaf0a06fb7f213e3131d31eb8d1f6e4ca63adb6df89b72489e915c57df8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
